
  # writeStats = true
  # [[cachebusters]]
  #   source = "assets/watching/hugo_stats\\.json"
  #   target = "styles\\.css"
  # [[cachebusters]]
  #   source = "(postcss|tailwind)\\.config\\.js"
  #   target = "css"
  # [[cachebusters]]
  #   source = "assets/.*\\.(js|ts|jsx|tsx)"
  #   target = "js"
  # [[cachebusters]]
  #   source = "assets/.*\\.(.*)$"
  #   target = "$1"